SOCKET_PATH = "/tmp/prime-switcher"
STARTUP_MODE_FILE_PATH = "/var/lib/prime_switcher/startup_mode"
DEFAULT_STARTUP_MODE = "inactive"
SYSTEM_CONFIGS_PATH = "/etc/prime_switcher/configs/"
XORG_CONF_PATH = "/etc/X11/xorg.conf.d/10-prime-switcher.conf"
XSETUP_PATH = "/bin/prime_switcher_Xsetup"
