#!/bin/sh
set -e
sv check dbus >/dev/null || exit 1
/usr/bin/python3 -u -m optimus_manager.hooks.pre_xorg_start
if [ -x /usr/bin/elogind-inhibit ]; then
        dbus-send --system --print-reply --dest=org.freedesktop.DBus \
                /org/freedesktop/DBus                           \
                org.freedesktop.DBus.StartServiceByName         \
                string:org.freedesktop.login1 uint32:0
fi
# respect system locale
[ -r /etc/locale.conf ] && . /etc/locale.conf && export LANG
exec sddm 2>&1

