#!/usr/bin/env python
import sys
import optimus_manager.envs as envs
from optimus_manager.config import load_config, ConfigError
from optimus_manager.var import read_startup_mode, write_startup_mode, read_requested_mode, remove_requested_mode_var, VarError
from optimus_manager.switching import switch_to_intel, switch_to_nvidia, SwitchError
from optimus_manager.cleanup import clean_autogenerated


def main():

    print("Optimus Manager (GPU setup) version %s" % envs.VERSION)

    print("Loading config")
    config = _get_config()

    print("Cleaning up previously generated files")
    clean_autogenerated()

    requested_mode = _get_requested_mode()
    print("Requested mode :", requested_mode)

    _setup_gpu(config, requested_mode)


def _get_config():

    try:
        config = load_config()
    except ConfigError as e:
        print("Error loading config file : %s" % str(e))
        sys.exit(1)

    return config


def _get_requested_mode():

    try:
        requested_mode = read_requested_mode()
    except VarError as e:

        print("Cannot read requested mode : %s.\nAssuming startup mode instead." % str(e))

        try:
            startup_mode = read_startup_mode()
        except VarError as e:
            print("Cannot read startup mode : %s.\nUsing default startup mode %s instead." % (str(e), envs.DEFAULT_STARTUP_MODE))
            startup_mode = envs.DEFAULT_STARTUP_MODE

        print("Startup mode :", startup_mode)
        if startup_mode == "nvidia_once":
            requested_mode = "nvidia"
            write_startup_mode("intel")
        else:
            requested_mode = startup_mode

    # We are done reading the command
    remove_requested_mode_var()

    return requested_mode


def _setup_gpu(config, requested_mode):

    try:
        if requested_mode == "nvidia":
            switch_to_nvidia(config)
        elif requested_mode == "intel":
            switch_to_intel(config)
    except SwitchError as e:
        print("Cannot setup GPU : %s" % str(e))
        sys.exit(0)


if __name__ == '__main__':
    main()
