#!/usr/bin/env sh
#Writen by Abhiram Shibu to easily run programs with nvidia gpu
export __NV_PRIME_RENDER_OFFLOAD=1 
export __GLX_VENDOR_LIBRARY_NAME="nvidia" 
export __VK_LAYER_NV_optimus="NVIDIA_only"
echo "Going to run" $@
$@
retvar=$?
echo "Program exited with code "$retvar
exit $retvar
