#!/usr/bin/env sh
#Writen by Abhiram Shibu to easily run programs with nvidia gpu
if [[ $(optimus-manager --status) == *"Current GPU mode : hybrid"* ]]
then
    if [ -z $@ ]
    then
        echo "Try nvrun <command>"
        exit -1
    else
        export __NV_PRIME_RENDER_OFFLOAD=1 
        export __GLX_VENDOR_LIBRARY_NAME="nvidia" 
        export __VK_LAYER_NV_optimus="NVIDIA_only"
        echo "Going to run" $@
        $@
        retvar=$?
        echo "Program exited with code "$retvar
        exit $retvar  
    fi
else
  echo "Sorry you are not in hybrid mode!"
  echo "Try optimus-manager --switch hybrid"
fi

