#!/bin/sh

REQUESTED_MODE_VAR_PATH="/var/lib/optimus-manager/requested_mode"

if [ -f $REQUESTED_MODE_VAR_PATH ]; then

    if [ $(cat $REQUESTED_MODE_VAR_PATH) = "nvidia" ]; then

        xrandr --setprovideroutputsource modesetting NVIDIA-0
        xrandr --auto
    fi
fi
