#! /bin/bash


post_install() {
	systemctl enable "optimus-manager.service"
}


post_upgrade () {
	RemoveBackupFiles
	systemctl daemon-reload
}


post_remove() {
	systemctl disable "optimus-manager.service"
	RemoveBackupFiles
	rm --force "/etc/optimus-manager/optimus-manager.conf"
	rm --force "/etc/X11/xorg.conf.d/10-optimus-manager.conf"
}


RemoveBackupFiles () {
	local Backup
	local Backups=(
		'etc/optimus-manager/nvidia-enable.sh'
		'etc/optimus-manager/nvidia-disable.sh'
		'etc/optimus-manager/optimus-manager.conf'
		'etc/optimus-manager/xorg/integrated-mode/integrated-gpu.conf'
		'etc/optimus-manager/xorg/nvidia-mode/integrated-gpu.conf'
		'etc/optimus-manager/xorg/nvidia-mode/nvidia-gpu.conf'
		'etc/optimus-manager/xorg/hybrid-mode/integrated-gpu.conf'
		'etc/optimus-manager/xorg/hybrid-mode/nvidia-gpu.conf'
		'etc/optimus-manager/xsetup-integrated.sh'
		'etc/optimus-manager/xsetup-nvidia.sh'
		'etc/optimus-manager/xsetup-hybrid.sh'
		'var/lib/optimus-manager/persistent/startup_mode'
	)

	for Backup in "${Backups[@]}}"; do
		rm --force "${Backup}."{pacnew,pacsave}*
	done
}
